openapi: 3.0.1
info:
  title: Tier 1 Gateway
  description: OpenAPI definition for the Tier 1 Gateway component of the SIMPL project
  contact:
    name: Simpl Programme
    url: https://simpl-programme.ec.europa.eu/
    email: cnect-simpl@ec.europa.eu
  license:
    name: European Union Public License (EUPL) 1.2
    url: https://interoperable-europe.ec.europa.eu/sites/default/files/custom-page/attachment/eupl_v1.2_en.pdf
  version: 1.5.0
servers:
- url: https://localhost:8080/v1
  description: Tier 1 Gateway
security:
- mtls: []
- mtlsWithEphemeralProof: []
- oauth2AuthCode: []
- oauth2ClientCredentials: []
tags:
- name: Application Info
  description: Retrieve information about the version of all the components
paths:
  /info/version:
    get:
      tags:
      - Application Info
      summary: Retrieve information about the version of all the components
      description: Retrieve information about the version of all the components running
        behind this tier 1 gateway
      operationId: version
      responses:
        "200":
          description: Version information returned successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GatewayInfoVersion"
      security: []
components:
  schemas:
    GatewayInfoVersion:
      type: object
      properties:
        components:
          type: array
          items:
            $ref: "#/components/schemas/ComponentVersion"
      required:
      - components
    ComponentVersion:
      type: object
      properties:
        name:
          type: string
          maxLength: 255
        version:
          type: string
          maxLength: 255
        details:
          type: string
          format: uri
      required:
      - name
      - version
  securitySchemes:
    mtls:
      type: http
      description: SIMPL Tier 2 mTLS authentication process
      scheme: mutual
    mtlsWithEphemeralProof:
      type: http
      description: SIMPL Tier 2 mTLS authentication process with Ephemeral Proof exchange
      scheme: mutual
    oauth2AuthCode:
      type: oauth2
      description: SIMPL Tier1 end users authentication process
      flows:
        authorizationCode:
          authorizationUrl: ""
          tokenUrl: ""
          scopes: {}
    oauth2ClientCredentials:
      type: oauth2
      description: SIMPL internal APIs authentication process
      flows:
        clientCredentials:
          tokenUrl: ""
          scopes: {}